name: "Pull Request Labeler"
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Uploads repository content to the runner
        with:
          repository: ${{ github.repository }}
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yml
