name: "Pull Request Labeler"
on:
  - pull_request_target
jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4 # Uploads repository content to the runner
        with:
          repository: metapox/mogura
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yml
